[WIP] About Us のコンテンツ作成
oystersjp/oystersjp.github.io pull request #12
Opened 2019-04-30 07:49 UTC by cocoeyes02

#3 About Us のコンテンツ作成 の実装 pull request

2019-04-30 08:05 UTC, IkezoeMakoto commented on hugo/data/about.yml
> +  content : ものづくり以外にも、サバゲーやダーツに行ったりゆるゆる遊んでいます！
すぐゆるゆる〜〜

2019-04-30 08:06 UTC, IkezoeMakoto requested changes
makeを実行してください！

2019-04-30 08:09 UTC, IkezoeMakoto commented
wipなの？レビューしちゃったけど

2019-04-30 08:10 UTC, cocoeyes02 commented
一旦あげてたので wip にしてました！
今は解除していますー！

2019-04-30 08:15 UTC, cocoeyes02 commented
あと make も実行しました！(たぶん)

2019-04-30 08:18 UTC, IkezoeMakoto approved these changes
よさそう

2019-04-30 08:25 UTC, BBCapMegane commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
githubの説明だと、`若手ものづくり集団`  だけど統一する？
(細かい表記揺れが気になる、申し訳)

2019-04-30 08:25 UTC, BBCapMegane commented on hugo/data/about.yml
> +  content : ものづくり以外にも、サバゲーやダーツに行ったりゆるゆる遊んでいます！
俺はおなかがゆるゆる〜〜

2019-04-30 08:27 UTC, IkezoeMakoto commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
確かに

2019-04-30 08:30 UTC, cocoeyes02 commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
確かに統一した方が良さげですねー！
文言的に余裕あるので、牡蠣好き 的な文章追加しても問題なさそうですが追加します？

2019-04-30 15:50 UTC, cocoeyes02 commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
> githubの説明だと、若手ものづくり集団 だけど統一する？

一旦こちらは修正しました！

2019-05-01 07:48 UTC, IkezoeMakoto commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
修正したらresolveにしてほしいなぁ

2019-05-01 07:49 UTC, IkezoeMakoto commented
マージしていいんでない？

2019-05-01 07:49 UTC, cocoeyes02 commented on hugo/data/about.yml
> +  content : Oysters は、若手クリエイターの集まりです！
> 文言的に余裕あるので、牡蠣好き 的な文章追加しても問題なさそうですが追加します？
こいつの反応なかったのでそのままにしてました
まあ、何もないってことはいらんってことだと思うので resolve にします！

2019-05-01 07:50 UTC, merged