feat: add member yu
oystersjp/oystersjp.github.io pull request #86
Opened 2021-02-01 13:33 UTC by Yu0614

2021-02-01 13:35 UTC, Yu0614 commented
@cocoeyes02 @mii288 

追加してみました〜！
README に 追加方法追記します？？

2021-02-01 13:39 UTC, mii288 requested changes

2021-02-01 13:39 UTC, mii288 commented on content/members/yu.ts
> +  github: 'Yu0614',
行末の `,` いらないかもです！

2021-02-01 23:26 UTC, Yu0614 commented on content/members/yu.ts
> +  github: 'Yu0614',
ありがとうございます。対応しました！

2021-02-02 00:42 UTC, mii288 commented
> @cocoeyes02 @mii288 
> 
> 
> 
> 追加してみました〜！
> 
> README に 追加方法追記します？？

はい！お願いしたいです！

2021-02-02 00:43 UTC, mii288 approved these changes

2021-02-02 01:44 UTC, cocoeyes02 approved these changes
LGTM
READMEの追記だけお願いしますー！

2021-02-03 15:21 UTC, Yu0614 commented
@cocoeyes02 

このPRでは README の改修は行わずに 別でPR作成しますね
ちょっとブランチの意図とずれてしまうので　

2021-02-10 07:11 UTC, Yu0614 commented
ほっとくとあれなんでとりあえずマージしますね(approveあざます)

2021-02-10 07:11 UTC, merged