feat: add how to add member
oystersjp/oystersjp.github.io pull request #87
Opened 2021-02-10 07:10 UTC by Yu0614

2021-02-10 07:12 UTC, Yu0614 commented
@mii288 @cocoeyes02 

書いてみました〜レビューよろしゅうです。

2021-02-10 07:27 UTC, mii288 requested changes
ありがとうございます！
2件コメントしたのでご確認ください〜！

2021-02-10 07:27 UTC, mii288 commented on README.md
> +    ```
```suggestion
    export default {
      name: 'your-name',
      // Save your profile image in `public/images/members`
      image: '/images/members/your-name.jpg',
      // Fill the belows. (Delete these properties if you don't need.) 
      twitter: 'your-twitter-id', 
      github: 'your-github-name',
      website: 'https://example.com/'
    }
```
ちょっとインデント含めて英文をメインに修正しました！
適宜修正していただけると mm

2021-02-10 07:27 UTC, mii288 commented on README.md
> +3. `images/members`にご自身の写真データを追加する。
```suggestion
3. `public/images/members`にご自身のプロフィール画像を追加する。
```
2に記載のサンプルコードのコメントに、プロフィール画像のことが書いてあるので、2と3逆は逆でも良いかも知れないですね。

2021-02-10 08:28 UTC, Yu0614 commented
@mii288 さん

コマンドで自動生成できるようにしたのでちと複雑になりました,すません
それに合わせて内容も書き換えました (・・;)

2021-02-10 08:32 UTC, Yu0614 commented on README.md
> +    ```
個々の部分なくなりました、すみません m(_)m

2021-02-10 08:35 UTC, Yu0614 commented on README.md
> +3. `images/members`にご自身の写真データを追加する。
最初に画像追加してもらうほうが わかりやすいので 1に持っていきました。
path は修正しておきますね

2021-02-10 09:16 UTC, mii288 approved these changes

2021-02-10 09:16 UTC, mii288 commented on .hygen/gen/intro/prompt.js
> +    validate: (answer /* string */) => {
hygenの引数の指定が分かってないんですが、`02` でも動きますか？

2021-02-10 09:16 UTC, mii288 commented on package.json
> +    "add-member": "npx hygen gen intro"
🥳  🌟 🌟 
```suggestion
    "add-member": "hygen gen intro"
```

依存パッケージに hygen を追加していただけますか？
`npm i -D hygen`

2021-02-10 09:16 UTC, mii288 commented on .hygen/gen/intro/introduction.ejs.t
> +
ここの空行は不要ですかね？
```suggestion
```

2021-02-10 09:20 UTC, mii288 commented
もしかして：実はhygenを動かすためにnodejsのインストール方法を記載する必要がある...？ 🤔

2021-02-10 09:30 UTC, mii288 commented on .hygen/gen/intro/prompt.js
> +    message: "What's your name?",
エラー文が日本語で、質問が英語なのでどっちかにしたい気持ち...！

@cocoeyes02  @Yu0614 とくにこだわりなければ日本語でいいかなと思うんですがどうですか？

2021-02-10 09:39 UTC, cocoeyes02 commented on .hygen/gen/intro/prompt.js
> +    message: "What's your name?",
日本語で良いと思います！

2021-02-10 09:46 UTC, cocoeyes02 approved these changes
ざっとみたけど、今あるコメント箇所対応したら良さそう

2021-02-11 05:50 UTC, Yu0614 commented on .hygen/gen/intro/prompt.js
> +    validate: (answer /* string */) => {
基本 コマンドラインから入力した文字は string として認識されるようで
1とか2 でもいけましたね

2021-02-11 05:52 UTC, Yu0614 commented on package.json
> +    "add-member": "npx hygen gen intro"
基本 人によってですが一回しか使わないので 依存関係として入れたくないなぁと思ってます。
なので npx で 起動してまする

2021-02-11 05:53 UTC, Yu0614 commented on .hygen/gen/intro/introduction.ejs.t
> +
b4a594358cef5899caa281fc25e0c15955 で対応しました。

2021-02-11 06:15 UTC, Yu0614 commented
@mii288 さん

> もしかして：実はhygenを動かすためにnodejsのインストール方法を記載する必要がある...？ 🤔

https://visualstudio.microsoft.com/ja/services/github-codespaces/

codespace で統一環境を提供するか...とか思ったんですが
かなり不安定なので ブラウザだときびしそう...

普通にぐぐっていただけばいいのでは？

2021-02-11 06:22 UTC, Yu0614 commented on .hygen/gen/intro/prompt.js
> +    message: "What's your name?",
どっちにするか迷ってたんですよね。ご指摘ありがたい。

日本語に統一します。

2021-02-11 06:25 UTC, mii288 commented on package.json
> +    "add-member": "npx hygen gen intro"
なるほど、、
最低限バージョンだけ指定した方がいいかなと思うんですが、どうでしょ？
(更新する人がnpmに明るい人とは限らないので)

`npx hygen@4’

2021-02-11 06:27 UTC, Yu0614 commented on package.json
> +    "add-member": "npx hygen gen intro"
>最低限バージョンだけ指定した方がいいかなと思うんですが、どうでしょ？

あー、動作保証してる最低限のバージョン...

そしたら依存関係に入れたほうが良さそうですね。 短慮でした。ご指摘ありがたいっす。
いれますね　

2021-02-11 06:27 UTC, Yu0614 commented on .hygen/gen/intro/prompt.js
> +    message: "What's your name?",
30a020e51ad095831d1c3fbdb9265b8d0b で対応

2021-02-11 06:28 UTC, Yu0614 commented on .hygen/gen/intro/prompt.js
> +    message: "What's your name?",
single と double 混ざってて気持ち悪かったのでそれも直しました

2021-02-11 06:29 UTC, mii288 commented
> @mii288 さん
> 
> 
> 
> > もしかして：実はhygenを動かすためにnodejsのインストール方法を記載する必要がある...？ 🤔
> 
> 
> 
> https://visualstudio.microsoft.com/ja/services/github-codespaces/
> 
> 
> 
> codespace で統一環境を提供するか...とか思ったんですが
> 
> かなり不安定なので ブラウザだときびしそう...
> 
> 
> 
> 普通にぐぐっていただけばいいのでは？
> 
> 

たしかに、優先順位も高くないので、調べてもらってで、いいかなと思います。

2021-02-11 06:30 UTC, Yu0614 commented on package.json
> +    "add-member": "npx hygen gen intro"
c1fb70146ea2ae0632ac1a34312ccb9731 で対応

2021-02-12 08:49 UTC, mii288 approved these changes
ありがとうございます！
マージお願いします 👍

2021-02-12 08:50 UTC, mii288 commented on .hygen/gen/intro/introduction.ejs.t
> +  image: '/images/members/<%= name %>.jpg',
すみません、こちら画像の拡張子はpng, gifもあり得るので修正していただけますか？

2021-02-12 08:50 UTC, mii288 reviewed
一箇所見落としてた部分があったのでコメントしました mm

2021-02-28 08:46 UTC, Yu0614 commented on .hygen/gen/intro/introduction.ejs.t
> +  image: '/images/members/<%= name %>.jpg',
d9b222df31bae456e4f1f8121c で対応しました！

2021-02-28 08:49 UTC, Yu0614 commented
マージします

2021-02-28 08:57 UTC, merged